version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postpaf-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postpaf-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: postpaf-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env
    networks:
      - postpaf-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: postpaf-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - postpaf-network

networks:
  postpaf-network:
    driver: bridge

volumes:
  postgres-data: